services:
#    warehouse_api.example:
#        class: WarehouseApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    warehouse_api.workflow.booking_workflow:
        class: WarehouseApiBundle\Workflow\BookingWorkflow
        arguments: ['@service_container']
    warehouse_api.workflow.container_workflow:
        class: WarehouseApiBundle\Workflow\ContainerWorkflow
        arguments: ['@service_container']
#    WarehouseApiBundle\Workflow\:
#            resource: '../../Workflow/*'
#            exclude: '../../Workflow/{BaseWorkflow}'
#            arguments: ['@service_container']
