services:
#    warehouse_api.example:
#        class: WarehouseApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    warehouse_api.workflow.booking_workflow:
        class: WarehouseApiBundle\Workflow\BookingWorkflow
        arguments: ['@service_container']
