version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/vhosts/rlogistic.roveconcepts.me/public_html
  - source: /
    destination: /var/www/vhosts/dx3pl.roveconcepts.me/public_html
  - source: /conf.d
    destination: /etc/httpd/conf.d
permissions:
  - object: /var/www
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
   - location: scripts/restart_apache.sh
     runas: ec2-user
