version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rlogistic/
  - source: /
    destination: /var/www/dx3pl/
hooks:
  BeforeInstall:
    - location: /conf/stopserver.sh
  AfterInstall:
    - location: /conf/startserver.sh
