# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    access_denied_url: /login
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    restapi:  { password: secretpw, roles: [ 'ROLE_API' ] }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            anonymous: ~
            pattern: ^/
            host: "%api_host%"
            http_basic:
                realm: "Demo REST API (username: restapi, password: secretpw)"
            stateless:  true
            provider: in_memory
        main:
            anonymous: ~
            pattern: ^/
            host: "%firewall_host%"
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            provider: fos_userbundle
            logout: true

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        #ROLE_SUPER_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: [ROLE_ADMIN, ROLE_API] }
        - { path: ^/, role: ROLE_USER }