services:
#    warehouse.example:
#        class: WarehouseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    twig.extension.app:
      class: WarehouseBundle\Twig\DemoExtension
      public: false
      arguments: ["@twig.loader"]
      tags:
          - { name: twig.extension }
    app.listener:
      class: WarehouseBundle\EventListener\ControllerListener
      arguments: ["@twig.extension.app"]
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    BookingManager:
      class: WarehouseBundle\Doctrine\BookingManager
      arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    ProductManager:
      class: WarehouseBundle\Doctrine\ProductManager
      arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]


    WarehouseBundle\Manager\:
        resource: '../../Manager/*'
        exclude: '../../Manager/{BaseManager}'
        arguments: ['@doctrine.orm.entity_manager']

    warehouse.manager.incoming_manager:
            class: WarehouseBundle\Manager\IncomingManager
            arguments: ['@doctrine.orm.entity_manager']

    WarehouseBundle\Workflow\:
        resource: '../../Workflow/*'
        exclude: '../../Workflow/{BaseWorkflow}'
        arguments: ['@service_container']
    WarehouseBundle\Utils\:
        resource: '../../Utils/*'
        arguments: ['@service_container']

    warehouse.hidden_datetime.form.type:
        class: WarehouseBundle\Form\Type\HiddenDateTimeType
        tags:
            - { name: form.type, alias: hidden_datetime } 
    warehouse.type.pick_queue_location:
        class: WarehouseBundle\Form\PickQueue\BookingPickQueueItemLocationDTOType
        tags:
            - { name: form.type, alias: form_booking_pick_queue_item_location_dto }
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.validator.not_modified:
        class: WarehouseBundle\Validator\Constraints\NotModifiedValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - {name: validator.constraint_validator, alias: not_modified}