services:
#    warehouse.example:
#        class: WarehouseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    twig.extension.app:
      class: WarehouseBundle\Twig\DemoExtension
      public: false
      arguments: ["@twig.loader"]
      tags:
          - { name: twig.extension }
    app.listener:
      class: WarehouseBundle\EventListener\ControllerListener
      arguments: ["@twig.extension.app"]
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    BookingManager:
      class: WarehouseBundle\Doctrine\BookingManager
      arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    ProductManager:
      class: WarehouseBundle\Doctrine\ProductManager
      arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    warehouse.manager.booking_manager:
        class: WarehouseBundle\Manager\BookingManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.product_manager:
        class: WarehouseBundle\Manager\ProductManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.user_manager:
        class: WarehouseBundle\Manager\UserManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.user_group_manager:
        class: WarehouseBundle\Manager\UserGroupManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.incoming_manager:
        class: WarehouseBundle\Manager\IncomingManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.location_product_manager:
        class: WarehouseBundle\Manager\LocationProductManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.incoming_status_manager:
        class: WarehouseBundle\Manager\IncomingStatusManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.incoming_product_scan_manager:
        class: WarehouseBundle\Manager\IncomingProductScanManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.incoming_product_manager:
        class: WarehouseBundle\Manager\IncomingProductManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.location_manager:
        class: WarehouseBundle\Manager\LocationManager
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.booking_comment_manager:
        class: WarehouseBundle\Manager\BookingCommentManager
        arguments: ['@doctrine.orm.entity_manager']

    warehouse.work_flow.booking_work_flow:
        class: WarehouseBundle\Workflow\BookingWorkflow
        arguments: ['@service_container']
    warehouse.workflow.user_workflow:
        class: WarehouseBundle\Workflow\UserWorkflow
        arguments: ['@service_container']
    warehouse.workflow.incoming_workflow:
        class: WarehouseBundle\Workflow\IncomingWorkflow
        arguments: ['@service_container']
    warehouse.workflow.incoming_product_scan_workflow:
        class: WarehouseBundle\Workflow\IncomingProductScanWorkflow
        arguments: ['@service_container']
    warehouse.workflow.staging_queue_workflow:
        class: WarehouseBundle\Workflow\StagingQueueWorkflow
        arguments: ['@service_container']
    warehouse.workflow.booking_comment_workflow:
        class: WarehouseBundle\Workflow\BookingCommentWorkflow
        arguments: ['@service_container']

    warehouse.utils.message_printer:
        class: WarehouseBundle\Utils\MessagePrinter
        arguments: ['@service_container']

    warehouse.hidden_datetime.form.type:
        class: WarehouseBundle\Form\Type\HiddenDateTimeType
        tags:
            - { name: form.type, alias: hidden_datetime } 
    warehouse.type.pick_queue_location:
        class: WarehouseBundle\Form\PickQueue\BookingPickQueueItemLocationDTOType
        tags:
            - { name: form.type, alias: form_booking_pick_queue_item_location_dto }
        arguments: ['@doctrine.orm.entity_manager']
    warehouse.validator.not_modified:
        class: WarehouseBundle\Validator\Constraints\NotModifiedValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - {name: validator.constraint_validator, alias: not_modified}