services:
#    warehouse.example:
#        class: WarehouseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    twig.extension.app:
      class: WarehouseBundle\Twig\DemoExtension
      public: false
      arguments: ["@twig.loader"]
      tags:
          - { name: twig.extension }
    app.listener:
      class: WarehouseBundle\EventListener\ControllerListener
      arguments: ["@twig.extension.app"]
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    BookingManager:
      class: WarehouseBundle\Doctrine\BookingManager
      arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    warehouse.manager.booking_manager:
      class: WarehouseBundle\Manager\BookingManager
      arguments: ['@doctrine.orm.entity_manager']
    warehouse.manager.product_manager:
      class: WarehouseBundle\Manager\ProductManager
      arguments: ['@doctrine.orm.entity_manager']
    warehouse.work_flow.booking_work_flow:
      class: WarehouseBundle\Workflow\BookingWorkflow
      arguments: ['@service_container']