<?php

namespace WarehouseBundle\Repository;

/**
 * BookingReturnProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingReturnProductRepository extends \Doctrine\ORM\EntityRepository
{
}
