<?php

namespace WarehouseBundle\Repository;
use WarehouseBundle\Entity\Booking;
use WarehouseBundle\Entity\BookingLog;

/**
 * BookingLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingLogRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Booking $booking
     * @param null $limit
     * @return BookingLog[]
     */
    public function getLogByBooking(Booking $booking, $limit=NULL) {
        return $this->createQueryBuilder('bl')
            ->andWhere('bl.booking = :booking')
            ->setParameter('booking', $booking)
            ->orderBy('bl.created','DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }
}
