<?php

namespace WarehouseBundle\Repository;

/**
 * BookingCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
