<?php

namespace WarehouseBundle\Repository;

/**
 * BookingContactCommunicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingContactCommunicationRepository extends \Doctrine\ORM\EntityRepository
{
}
