<?php

namespace WarehouseBundle\Repository;

/**
 * BookingContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingContactRepository extends \Doctrine\ORM\EntityRepository
{
}
