<?php

namespace WarehouseBundle\Repository;

/**
 * BookingProductLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingProductLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
