<?php

namespace WarehouseBundle\Repository;

/**
 * BookingFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingFileRepository extends \Doctrine\ORM\EntityRepository
{
}
