<?php

namespace WarehouseBundle\Repository;

use Doctrine\ORM\Query\Expr;

/**
 * BookingReturnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingReturnRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Find a group of matching Returns by model, order number, or order reference.
	 *
	 * @param      string  $searchString  The search string
	 * @param      <type>  $limit  The limit
	 *
	 * @return     <type>  ( description_of_the_return_value )
	 */
	public function findByModelOrOrder($searchString,$limit=null) {
		$query = $this->createQueryBuilder('r')
           ->join('WarehouseBundle:Booking','b','WITH','b.id = r.booking')
           ->join('WarehouseBundle:BookingReturnProduct','rp','WITH','r.id = rp.bookingReturn')
           ->join('WarehouseBundle:Product','p','WITH','p.id = rp.product')
           ->andWhere(Expr::orX(
           		Expr::like('p.model',':searchString'),
           		Expr::like('b.orderNumber',':searchString'),
           		Expr::like('b.orderReference',':searchString')
           	))
           ->setParameter('searchString', $searchString.'%')
           ->groupBy('r.id')
           ->orderBy('r.id','DESC');
        if (!is_null($limit) && is_integer($limit))
           $query->setMaxResults(10);
        return $query->getQuery()->getResult();
	}
}
