<?php

namespace WarehouseBundle\Repository;

use Doctrine\ORM\Query\Expr;
use WarehouseBundle\Entity\Booking;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Find a group of matching Bookings by model.
	 *
	 * @param      string  $searchString  The search string
	 * @param      <type>  $limit  The limit
	 *
	 * @return     <type>  ( description_of_the_return_value )
	 */
	public function findByModelOrOrder($searchString,$limit=null) {
		$query = $this->createQueryBuilder('b')
           ->join('WarehouseBundle:BookingProduct','bp','WITH','b.id = bp.booking')
           ->join('WarehouseBundle:Product','p','WITH','p.id = bp.product')
           ->andWhere(Expr::orX(
           		Expr::like('p.model',':searchString'),
           		Expr::like('b.orderNumber',':searchString'),
           		Expr::like('b.orderReference',':searchString')
           	))
           ->setParameter('searchString', $searchString.'%')
           ->orderBy('b.orderNumber','ASC');
        if (!is_null($limit) && is_integer($limit))
           $query->setMaxResults(10);
        return $query->getQuery()->getResult();
	}
}
