<?php

namespace WarehouseBundle\Repository;

/**
 * BookingReturnCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingReturnCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
