<?php

namespace WarehouseBundle\Repository;

/**
 * IncomingFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomingFileRepository extends \Doctrine\ORM\EntityRepository
{
}
