<?php

namespace WarehouseBundle\Repository;

/**
 * IncomingCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomingCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
