<?php

namespace WarehouseBundle\Repository;

use Doctrine\ORM\EntityRepository;
use WarehouseBundle\Entity\Incoming;
use WarehouseBundle\Entity\IncomingProduct;
use WarehouseBundle\Entity\Product;

/**
 * IncomingProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomingProductRepository extends EntityRepository
{
	/**
	 * Gets the previously picked booking products by product
	 *
	 * @param Product $product
	 * @param null    $limit
	 *
	 * @return array
	 */
	public function getIncomingByProduct(Product $product, $limit = NULL)
	{
		return $this->createQueryBuilder('ip')
			->andWhere('ip.product = :product')
			->join('WarehouseBundle:Incoming', 'i')
			->andWhere('i.status IN (:incoming_status)')
			->setParameter('product', $product)
			->setParameter('incoming_status', [1, 2])# TODO: Verify with art these statuses (This is all statuses)
			->addSelect('(
            	CASE WHEN i.arrived IS NOT NULL THEN 1
            		 ELSE (
		            	CASE WHEN i.scheduled IS NOT NULL THEN i.scheduled
		            		 ELSE i.eta
		            	END
		             )
            	END
            ) AS HIDDEN ORD')
			->orderBy('ORD', 'DESC')
			->setMaxResults($limit ? $limit : 10000)
			->getQuery()
			->getResult();
	}

	/**
	 * Find a group of matching Products by model
	 *
	 * @param string $searchString
	 * @param null   $limit
	 *
	 * @return array
	 */
	public function findByModelOrName(string $searchString, $limit = null)
	{
		$query = $this->createQueryBuilder('ip');
		$query->innerJoin('WarehouseBundle:Product', 'p', 'WITH', 'p.id = ip.product')
			->innerJoin('WarehouseBundle:Incoming', 'i', 'WITH', 'ip.incoming = i.id')
			->where('i.status IN (:status)')
			->andWhere($query->expr()->orX(
				$query->expr()->like('p.model', ':searchString'),
				$query->expr()->like('i.name', ':searchString')
			))
			->setParameter('searchString', $searchString . '%')
			->setParameter('status', [1, 2])
			->orderBy('i.id', 'ASC');
		if (!is_null($limit) && is_integer($limit))
			$query->setMaxResults(10);
		return $query->getQuery()->getResult();
	}

	/**
	 * Find IncomingProduct by Incoming and model.
	 *
	 * @param Incoming $incoming
	 * @param string   $model
	 *
	 * @return mixed|IncomingProduct
	 */
	function findOneByModel(Incoming $incoming, string $model)
	{
		return $this->createQueryBuilder('ip')
			->join('WarehouseBundle:Product', 'p', 'WITH', 'ip.product = p.id')
			->andWhere('ip.incoming = :incoming')
			->andWhere('p.model = :model')
			->setParameter('incoming', $incoming)
			->setParameter('model', $model)
			->setMaxResults(1)
			->getQuery()
			->getOneOrNullResult();
	}
}
