<?php

namespace WarehouseBundle\Repository;

/**
 * IncomingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomingRepository extends \Doctrine\ORM\EntityRepository
{
}
