<?php

namespace WarehouseBundle\Repository;

/**
 * IncomingStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomingStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
