<?php

namespace WarehouseBundle\Repository;

/**
 * IncomingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
