<?php

namespace WarehouseBundle\Repository;

/**
 * LocationProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationProductRepository extends \Doctrine\ORM\EntityRepository
{

	public function findOneByProductAndLocation(\WarehouseBundle\Entity\Product $product,\WarehouseBundle\Entity\Location $location) {
		return $this->createQueryBuilder('pl')
			->andWhere('pl.product = :product')
			->andWhere('pl.location = :location')
			->setParameter('product',$product)
			->setParameter('location',$location)
			->setMaxResults(1)
			->getQuery()
			->getOneOrNullResult();
	}

}