<?php

namespace WarehouseBundle\Repository;

/**
 * ProductLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLogRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Get all log entries by product
	 *
	 * @param      \WarehouseBundle\Entity\Product  $product  The product
	 * @param       integer $limit The max number of results to return.
	 *
	 * @return     <type>                           The log by product.
	 */
	public function getLogByProduct(\WarehouseBundle\Entity\Product $product, $limit=NULL) {
		return $this->createQueryBuilder('pl')
			->andWhere('pl.product = :product')
            ->setParameter('product', $product)
            ->orderBy('pl.created','DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
	}

}
